### ISSUE TITLE
unwrap on null (connect/disconnect multiple time)

### ISSUE THREAD

**Issue by davidbarre** [mikeycgto/esper#14]
This issue happens on trying to connect/disconnect multiple time 

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /(...)/nightly-dist-rustc-linux/build/src/libcore/option.rs:323

stack backtrace:
ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=kernel pid=397 comm="esper" exe="/(...)/target/release/esper" sig=11
```

To reproduce just in a terminal , I repeat this 3 ... 5 ... 10 times 
```
curl -v -X GET http://domain.tld/subscribe/abcdef123
CTRL+C
curl -v -X GET http://domain.tld/subscribe/abcdef123
CTRL+C
(...)
```

**Comment by mikeycgto** [comment]
I'm not able to reproduce this. Could you run esper with these env vars set?

```
RUST_BACKTRACE=1 RUST_LOG=debug
```

**Comment by davidbarre** [comment]
```
DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }
INFO:esper::handler: POST /publish/abcdef123
DEBUG:esper::handler: Found JWT parameter of None
DEBUG:esper::handler: POST /publish req_readable
DEBUG:esper::handler: POST /publish on_response
INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ControlError(())', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:870
stack backtrace:
   1:        0x10143e8fc - std::sys::imp::backtrace::tracing::imp::write::h36dcd6719b30e145
   2:        0x10144077e - std::panicking::default_hook::{{closure}}::h4ef47a6ed549d2e6
   3:        0x101440420 - std::panicking::default_hook::hd7b4c7a7e16abb43
   4:        0x101440c37 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   5:        0x101440ae4 - std::panicking::begin_panic::h3b15a7df583e5416
   6:        0x101440a02 - std::panicking::begin_panic_fmt::h4c0c43306d52c68f
   7:        0x101440967 - rust_begin_unwind
   8:        0x101468640 - core::panicking::panic_fmt::hbd633f652cd3a047
   9:        0x10135f8f6 - core::result::unwrap_failed::h494fe2145e9c48a2
  10:        0x1013707f9 - esper::Manager::publish::h082bba83dfb4c354
  11:        0x101369ac2 - <esper::handler::EventStream as hyper::server::Handler<hyper::net::HttpStream>>::on_response::hba022b3a187694ba
  12:        0x10135644e - <hyper::http::conn::ConnInner<K, T, H>>::on_writable::h8c54a809895d8c90
  13:        0x101354376 - <hyper::http::conn::Conn<K, T, H>>::ready::h5c4be94ca396b84e
  14:        0x10134920c - <mio::event_loop::EventLoop<H>>::run_once::h92fc0fc88767b156
  15:        0x10134f96f - drop::h0d3108231d9f8ddd
  16:        0x101347ce9 - std::panicking::try::do_call::h5b25b88105e14cf7
  17:        0x101441b7a - __rust_maybe_catch_panic
  18:        0x101352180 - <F as alloc::boxed::FnBox<A>>::call_box::h4b2d3c901617c2ea
  19:        0x10143fef4 - std::sys::imp::thread::Thread::new::thread_start::he1b44499d44cc4a4
  20:     0x7fffc3b6daaa - _pthread_body
  21:     0x7fffc3b6d9f6 - _pthread_start
```

**Comment by davidbarre** [comment]
```
#cargo --version
cargo 0.17.0-nightly (6c79cf9 2017-01-13)
#rustc --version
rustc 1.16.0-nightly (bf6d7b665 2017-01-15)
#uname -a
Darwin MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

on another linux machine, I got this :

```
2017-01-17T23:48:53.125327577Z INFO:esper::handler: POST /publish/abcdef123
2017-01-17T23:48:53.125334270Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-17T23:48:53.125340163Z DEBUG:esper::handler: POST /publish req_readable
2017-01-17T23:48:53.125345657Z DEBUG:esper::handler: POST /publish on_response
2017-01-17T23:48:53.125351051Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-17T23:48:53.125357744Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Tue, 17 Jan 2017 23:48:53 GMT, Transfer-Encoding: chunked, }
2017-01-17T23:48:53.126001222Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("ea68c5de-402d-4b3d-8792-29904ba8c28f") }
2017-01-17T23:48:53.126038780Z DEBUG:esper::handler: Transport wrote message
2017-01-17T23:48:53.126504359Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") }
2017-01-17T23:48:53.126534824Z DEBUG:esper::handler: Transport wrote message
2017-01-17T23:48:53.127224152Z DEBUG:hyper::http::conn: io error trying to parse Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("parse eof") }) }
2017-01-17T23:48:53.127268502Z DEBUG:hyper::http::conn: on_remove
2017-01-17T23:48:53.899771306Z DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
2017-01-17T23:48:53.899898363Z DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }

2017-01-17T23:48:53.899913546Z INFO:esper::handler: POST /publish/abcdef123
2017-01-17T23:48:53.899922436Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-17T23:48:53.899929628Z DEBUG:esper::handler: POST /publish req_readable
2017-01-17T23:48:53.899936920Z DEBUG:esper::handler: POST /publish on_response
2017-01-17T23:48:53.899944212Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-17T23:48:53.899951903Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Tue, 17 Jan 2017 23:48:53 GMT, Transfer-Encoding: chunked, }
2017-01-17T23:48:53.899959894Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("ea68c5de-402d-4b3d-8792-29904ba8c28f") }
2017-01-17T23:48:53.901810820Z DEBUG:esper::handler: Transport wrote message
2017-01-17T23:48:53.901840887Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") }
2017-01-17T23:48:53.901851375Z DEBUG:esper::handler: Transport wrote message
2017-01-17T23:48:53.903821567Z DEBUG:hyper::http::conn: io error trying to parse Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("parse eof") }) }
2017-01-17T23:48:53.903857227Z DEBUG:hyper::http::conn: on_remove
2017-01-17T23:48:54.833666147Z DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
2017-01-17T23:48:54.833722384Z DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }

2017-01-17T23:48:54.833778222Z INFO:esper::handler: POST /publish/abcdef123
2017-01-17T23:48:54.833815480Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-17T23:48:54.833843149Z DEBUG:esper::handler: POST /publish req_readable
2017-01-17T23:48:54.833880407Z DEBUG:esper::handler: POST /publish on_response
2017-01-17T23:48:54.833910274Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.833934846Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Tue, 17 Jan 2017 23:48:54 GMT, Transfer-Encoding: chunked, }
2017-01-17T23:48:54.833958819Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") }
2017-01-17T23:48:54.835768991Z DEBUG:esper::handler: Transport wrote message
2017-01-17T23:48:54.835808347Z DEBUG:hyper::http::conn: on_error err = Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
2017-01-17T23:48:54.835822531Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835832020Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835841110Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835849201Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835857891Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835868879Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835909933Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835935504Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835944694Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835953384Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835961775Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835970165Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835978556Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835987046Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.835996336Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.836004826Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.836013217Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.836022107Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.836044682Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.836054770Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }
2017-01-17T23:48:54.836063760Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("ea68c5de-402d-4b3d-8792-29904ba8c28f") }
2017-01-17T23:48:54.836840989Z DEBUG:esper::handler: Transport wrote message
2017-01-17T23:48:54.836876450Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("480dfb57-3e1f-45a3-a8ec-ebd2c8c2b798") } to topic Topic { id: "abcdef123" }

( same message, again and again)

```

**Comment by davidbarre** [comment]
I try my best to be clear


```
(at this point, there is no curl suscriber launched, I just exited two previous curl suscriber)

(I launch one new curl suscriber => 90b9730c-02fd-48d0-9b3e-bd733fdf0313)
2017-01-18T00:11:24.244255407Z DEBUG:hyper::server::request: Request Line: Get AbsolutePath { path: "/subscribe/abcdef123", query: None } Http11
2017-01-18T00:11:24.244403341Z DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, }
2017-01-18T00:11:24.244422420Z INFO:esper::handler: GET /subscribe/abcdef123
2017-01-18T00:11:24.244435305Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-18T00:11:24.244445793Z DEBUG:esper::handler: GET /subscribe on_response
2017-01-18T00:11:24.244457280Z INFO:esper: [Manager] Subscribe client Client { id: Uuid("90b9730c-02fd-48d0-9b3e-bd733fdf0313") } to topic Topic { id: "abcdef123" }

(I post a message)
2017-01-18T00:11:24.244991781Z DEBUG:hyper::http::h1::parse: writing Headers { Content-Type: text/event-stream, Date: Wed, 18 Jan 2017 00:11:24 GMT, Transfer-Encoding: chunked, }
2017-01-18T00:11:44.971868325Z DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
2017-01-18T00:11:44.971988490Z DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }
2017-01-18T00:11:44.972126635Z INFO:esper::handler: POST /publish/abcdef123
2017-01-18T00:11:44.972250196Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-18T00:11:44.972552557Z DEBUG:esper::handler: POST /publish req_readable
2017-01-18T00:11:44.973349363Z DEBUG:esper::handler: POST /publish on_response
2017-01-18T00:11:44.973475122Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-18T00:11:44.973666207Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Wed, 18 Jan 2017 00:11:44 GMT, Transfer-Encoding: chunked, }

(esper send 3 messages)
2017-01-18T00:11:44.973720147Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("90b9730c-02fd-48d0-9b3e-bd733fdf0313") }
(90b9730c-02fd-48d0-9b3e-bd733fdf0313 my new one)
2017-01-18T00:11:44.973798359Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:44.973827426Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") }
(exited suscriber)
2017-01-18T00:11:44.973951387Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:44.976075503Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("3b51ac00-e2fc-4279-aa5c-c825171a61ff") }
(exited suscriber bis)
2017-01-18T00:11:44.976176889Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:44.976870211Z DEBUG:hyper::http::conn: io error trying to parse Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("parse eof") }) }
2017-01-18T00:11:44.976925948Z DEBUG:hyper::http::conn: on_remove
2017-01-18T00:11:49.107384160Z DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
2017-01-18T00:11:49.107456879Z DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }

( I post another message)

2017-01-18T00:11:49.108076483Z INFO:esper::handler: POST /publish/abcdef123
2017-01-18T00:11:49.109556322Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-18T00:11:49.109626743Z DEBUG:esper::handler: POST /publish req_readable
2017-01-18T00:11:49.109642426Z DEBUG:esper::handler: POST /publish on_response
2017-01-18T00:11:49.109652315Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-18T00:11:49.109662903Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Wed, 18 Jan 2017 00:11:49 GMT, Transfer-Encoding: chunked, }

(esper send 3 messages)
2017-01-18T00:11:49.109672991Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("90b9730c-02fd-48d0-9b3e-bd733fdf0313") }
2017-01-18T00:11:49.110885530Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:49.110932877Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") }
2017-01-18T00:11:49.112860214Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:49.112904265Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("3b51ac00-e2fc-4279-aa5c-c825171a61ff") }
2017-01-18T00:11:49.112919448Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:49.116166903Z DEBUG:hyper::http::conn: io error trying to parse Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("parse eof") }) }
2017-01-18T00:11:49.116240720Z DEBUG:hyper::http::conn: on_remove

(I post another message)

2017-01-18T00:11:51.549751211Z DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
2017-01-18T00:11:51.550462213Z DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }
2017-01-18T00:11:51.550489982Z INFO:esper::handler: POST /publish/abcdef123
2017-01-18T00:11:51.550501369Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-18T00:11:51.551938456Z DEBUG:esper::handler: POST /publish req_readable
2017-01-18T00:11:51.551988001Z DEBUG:esper::handler: POST /publish on_response
2017-01-18T00:11:51.552003483Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.552016369Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Wed, 18 Jan 2017 00:11:51 GMT, Transfer-Encoding: chunked, }

(esper try to send 3 messages)
2017-01-18T00:11:51.552027157Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("90b9730c-02fd-48d0-9b3e-bd733fdf0313") }
2017-01-18T00:11:51.552037345Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:51.552047134Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") }
2017-01-18T00:11:51.554932096Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:51.554965658Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("3b51ac00-e2fc-4279-aa5c-c825171a61ff") }
2017-01-18T00:11:51.554978144Z DEBUG:esper::handler: Transport wrote message
2017-01-18T00:11:51.554987834Z DEBUG:hyper::http::conn: on_error err = Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
(!!!! broken pipe ~30-40sec after exited)
2017-01-18T00:11:51.555002317Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") } to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.555012406Z DEBUG:hyper::http::conn: on_error err = Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
(!!!! broken pipe ~30-40sec after exited)
2017-01-18T00:11:51.555022395Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("3b51ac00-e2fc-4279-aa5c-c825171a61ff") } to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.555032384Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") } to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.555042073Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("3b51ac00-e2fc-4279-aa5c-c825171a61ff") } to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.555052561Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") } to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.555062550Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("3b51ac00-e2fc-4279-aa5c-c825171a61ff") } to topic Topic { id: "abcdef123" }
2017-01-18T00:11:51.555072938Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("86a20cda-803c-4406-9462-39616ad2cbfa") } to topic Topic { id: "abcdef123" }
(infinite loop)
```

**Comment by mikeycgto** [comment]
The latest push should fix this.

Overall, this project is not as stable as it should be. Rewriting esper to use hyper's new API is the first step in improving stable. I'm not sure when I will have time to work on it again but hopefully I can soon!

**Comment by davidbarre** [comment]
Thanks for the new commit but it's not better :

with `RUST_BACKTRACE=1 RUST_LOG=debug` : esper don't crash but i can't connect to the server.
I'll try on linux after, my last test full up my filesystem with log :-)

``` 
DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }
INFO:esper::handler: POST /publish/abcdef123
DEBUG:esper::handler: Found JWT parameter of None
DEBUG:esper::handler: POST /publish req_readable
DEBUG:esper::handler: POST /publish on_response
INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ControlError(())', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:870
stack backtrace:
   1:        0x109dae83c - std::sys::imp::backtrace::tracing::imp::write::h36dcd6719b30e145
   2:        0x109db06be - std::panicking::default_hook::{{closure}}::h4ef47a6ed549d2e6
   3:        0x109db0360 - std::panicking::default_hook::hd7b4c7a7e16abb43
   4:        0x109db0b77 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   5:        0x109db0a24 - std::panicking::begin_panic::h3b15a7df583e5416
   6:        0x109db0942 - std::panicking::begin_panic_fmt::h4c0c43306d52c68f
   7:        0x109db08a7 - rust_begin_unwind
   8:        0x109dd8580 - core::panicking::panic_fmt::hbd633f652cd3a047
   9:        0x109ccf736 - core::result::unwrap_failed::h494fe2145e9c48a2
  10:        0x109ce0731 - esper::Manager::publish::h082bba83dfb4c354
  11:        0x109cd9962 - <esper::handler::EventStream as hyper::server::Handler<hyper::net::HttpStream>>::on_response::hba022b3a187694ba
  12:        0x109cc64ce - <hyper::http::conn::ConnInner<K, T, H>>::on_writable::h8c54a809895d8c90
  13:        0x109cc43f6 - <hyper::http::conn::Conn<K, T, H>>::ready::h5c4be94ca396b84e
  14:        0x109cb928c - <mio::event_loop::EventLoop<H>>::run_once::h92fc0fc88767b156
  15:        0x109cbf9ef - drop::h0d3108231d9f8ddd
  16:        0x109cb7d69 - std::panicking::try::do_call::h5b25b88105e14cf7
  17:        0x109db1aba - __rust_maybe_catch_panic
  18:        0x109cc2200 - <F as alloc::boxed::FnBox<A>>::call_box::h4b2d3c901617c2ea
  19:        0x109dafe34 - std::sys::imp::thread::Thread::new::thread_start::he1b44499d44cc4a4
  20:     0x7fffc3b6daaa - _pthread_body
  21:     0x7fffc3b6d9f6 - _pthread_start
DEBUG:hyper::server::request: Request Line: Post AbsolutePath { path: "/publish/abcdef123", query: None } Http11
DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, Content-Length: 35, Content-Type: application/x-www-form-urlencoded, }

(after crash publish)

INFO:esper::handler: POST /publish/abcdef123
DEBUG:esper::handler: Found JWT parameter of None
DEBUG:esper::handler: POST /publish req_readable
DEBUG:esper::handler: POST /publish on_response
WARN:esper::handler: Failed to lock manager
DEBUG:hyper::http::h1::parse: writing Headers { Date: Wed, 18 Jan 2017 13:57:45 GMT, Transfer-Encoding: chunked, }
DEBUG:hyper::http::conn: io error trying to parse Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("parse eof") }) }
DEBUG:hyper::http::conn: on_remove
DEBUG:hyper::server::request: Request Line: Get AbsolutePath { path: "/subscribe/abcdef123", query: None } Http11
DEBUG:hyper::server::request: Headers { Host: localhost:3000, User-Agent: curl/7.49.1, Accept: */*, }

(after crash suscribe)

INFO:esper::handler: GET /subscribe/abcdef123
DEBUG:esper::handler: Found JWT parameter of None
DEBUG:esper::handler: GET /subscribe on_response
WARN:esper::handler: Failed to lock manager!
DEBUG:hyper::http::h1::parse: writing Headers { Content-Type: text/event-stream, Date: Wed, 18 Jan 2017 13:58:11 GMT, Transfer-Encoding: chunked, }
DEBUG:hyper::http::conn: io error trying to parse Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("parse eof") }) }
DEBUG:hyper::http::conn: on_remove
``` 

without `RUST_BACKTRACE=1 RUST_LOG=debug`

```
Welcome to esper -- the Event Source HTTP server, powered by hyper!

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ControlError(())', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:870
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:870
```

**Comment by davidbarre** [comment]
linux result

```
2017-01-18T14:12:47.059511031Z INFO:esper::handler: POST /publish/abcdef123
2017-01-18T14:12:47.059517173Z DEBUG:esper::handler: Found JWT parameter of None
2017-01-18T14:12:47.059521430Z DEBUG:esper::handler: POST /publish req_readable
2017-01-18T14:12:47.059525782Z DEBUG:esper::handler: POST /publish on_response
2017-01-18T14:12:47.059530257Z INFO:esper: [Manager] Publish to topic Topic { id: "abcdef123" }
2017-01-18T14:12:47.059535624Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("eb8779c9-792e-4c01-9824-7c1e15c633dc") }
2017-01-18T14:12:47.060259991Z DEBUG:esper::handler: Transport wrote message
2017-01-18T14:12:47.060341799Z INFO:esper: [Manager] Retrieving messages for Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") }
2017-01-18T14:12:47.060355000Z DEBUG:esper::handler: Transport wrote message
2017-01-18T14:12:47.060362943Z DEBUG:hyper::http::h1::parse: writing Headers { Date: Wed, 18 Jan 2017 14:12:47 GMT, Transfer-Encoding: chunked, }
2017-01-18T14:12:47.062846589Z DEBUG:hyper::http::conn: on_error err = Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
2017-01-18T14:12:47.062879232Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") } to topic Topic { id: "abcdef123" }
2017-01-18T14:12:47.062884544Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") } to topic Topic { id: "abcdef123" }
2017-01-18T14:12:47.062887893Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") } to topic Topic { id: "abcdef123" }
2017-01-18T14:12:47.062891264Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") } to topic Topic { id: "abcdef123" }
2017-01-18T14:12:47.062894612Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") } to topic Topic { id: "abcdef123" }
2017-01-18T14:12:47.062920836Z INFO:esper: [Manager] Unsubscribe client Client { id: Uuid("81bacbbe-fc2f-4bb9-b60b-fa9ef260d52c") } to topic Topic { id: "abcdef123" }

```

**Comment by davidbarre** [comment]
I delete my `target` and `.cargo` before second test

**Comment by mikeycgto** [comment]
Push another small commit which should handle this crash. There were 2 places in the `publish` function that I wasn't handling unexpected results as fully as possible.

Again, this should help improve stability but I wouldn't call esper stable yet.

**Comment by davidbarre** [comment]
Great ! Can't reproduce on my mac the `'<unnamed>' panicked at 'called Option::unwrap()`

but In fact, I think there are two differents issues here.

because I still have the infinite loop on linux : 
```[Manager] Unsubscribe client Client ...
[Manager] Unsubscribe client Client ...
[Manager] Unsubscribe client Client ...```
with CPU load of 100%
*BUT* esper don't crash now 👍  it's still working with a high load 

If I remove debug log and backtrace, I don't have the infinite message but CPU load of the process goes to 100% ...

I will try on another linux server to see, because I only see this issue on linux and not on my local mac

**Comment by davidbarre** [comment]
yep same behaviour on fresh debian jessie install

![image](https://cloud.githubusercontent.com/assets/2768671/22089054/e8cc6dba-dde8-11e6-815c-08648e4a7d8c.png)

**Comment by mikeycgto** [comment]
Is this with the latest master?

http://michaeljcoyne.me

**Comment by davidbarre** [comment]
yes : new server, new rust install, new git clone

**Comment by mikeycgto** [comment]
Helps if I actually push my changes :laughing:. I updated Hyper to just before the new API changes and I think that should improve stability. Please try again.

If you don't mind me asking, what are you interested in esper for?

**Comment by davidbarre** [comment]
OK I test the last commit on new fresh Ubuntu Xenial server and my debian jessie docker 

=> it works fine 👍 

------------

(not important) docopt_macros doesn't compile with last nightly version... I downgrade on nightly-2017-01-12

------------

I'm looking for a SSE server independent box.
I don't want to write long running php script for example or thing like this

What I like in esper : 
- simplicity
- independent service
- just 2 url IN & OUT (so another backend can publish message)
- [my hosting provider](https://www.clever-cloud.com/) can compile, deploy and run a git rust projet (PAAS) 
- On top of that, I use JWT in my company...
- and I want to learn Rust so it's a good use case

I didn't find any equivalent, maybe you know one ?
What is your motivation on your side, to start this projet ?

**Comment by mikeycgto** [comment]
I wrote this mainly to learn Rust and Hyper. There doesn't seem to be that many standalone SSE servers around so I figured it would be a good area to explore.

I do hope to rewrite esper soon and try to get an actual Alpha Release sooner than later though. Thanks for trying it out and working through these issues with me!
